import type { BrandProduct } from "@/components/BrandProductSalesPage";
import brandKitImage from "@/assets/product-brand-kit.jpg";
import workbookImage from "@/assets/product-workbook.jpg";
import aiPromptKitImage from "@/assets/product-ai-prompt-kit.jpg";

export const brandKitProduct: BrandProduct = {
  eyebrow: "Private Strategy Suite",
  name: "The Dollhouse Brand Kit",
  shortName: "Brand Kit",
  price: "$97",
  regular: "$145",
  value: "$497 value · instant access after purchase",
  checkoutUrl: "",
  tagline: "Not a template. A complete brand strategy system — built by you, inside your own private studio.",
  intro: "This is your private place to organize the brand foundation, offer, content direction, launch roadmap, and business vision you keep trying to piece together from random advice.",
  painHeadline: "Stop guessing what your brand should look like.",
  painBody: "If you are tired of overthinking your brand, second guessing every move, buying random templates, and posting without seeing results, The Dollhouse gives you one guided system to follow. No fluff, no confusing jargon, no guessing.",
  imageTitle: "Brand Kit",
  imageSubtitle: "Your complete brand strategy, product plan, and launch roadmap built for you inside a private web app.",
  imageItems: ["17 guided rooms", "Custom strategy plan", "Save & export", "Private access"],
  insideTitle: "17 guided strategy rooms for building the full brand foundation.",
  inside: [
    { title: "Brand Foundation", body: "Define your mission, values, voice, identity, and the direction your brand should be known for." },
    { title: "Offer & Product Planning", body: "Create offers, products, pricing, and positioning that make your brand easier to understand and buy from." },
    { title: "Launch Roadmap", body: "Turn the foundation into a clear launch plan with goals, content direction, and next steps." },
    { title: "Audience Clarity", body: "Get clear on who you serve, what they want, what they need, and why they should trust you." },
    { title: "Marketing Strategy", body: "Plan your content, visibility, social direction, website checklist, and brand messaging in one place." },
    { title: "Export & Save Tools", body: "Keep your strategy organized and save your plan so it is not scattered across notes and screenshots." },
  ],
  outcomes: [
    "Build your brand with a guided step-by-step strategy roadmap.",
    "Create offers, content, and launch plans without feeling overwhelmed.",
    "Organize your ideas, goals, and business vision all in one place.",
    "Walk away with your entire brand foundation locked in — colours, voice, offer, and direction.",
  ],
  perfectFor: [
    "New business owners who need direction before they invest in monthly marketing.",
    "Beauty brands, boutiques, coaches, creators, influencers, and digital product sellers.",
    "Women building online brands who want a beautiful strategy system that feels simple.",
    "Beginners who want to finish the foundation before hiring The Dollhouse for done-for-you growth.",
  ],
  bonuses: [
    "Content planning support",
    "Guided prompts",
    "Brand strategy worksheets",
    "Launch planning sections",
    "Goal tracking areas",
    "Future updates",
  ],
  faqs: [
    { q: "Is this a mobile app?", a: "No. The Dollhouse is a private interactive web app designed to work beautifully through your browser, especially on laptop and tablet." },
    { q: "Is this beginner friendly?", a: "Yes. Everything is guided, simple, aesthetic, and made for beginners who are starting from scratch." },
    { q: "How do I access it?", a: "You receive instant private access after purchase through the product link." },
    { q: "Can I hire The Dollhouse after I finish it?", a: "Yes. Once your foundation is clear, you can apply for managed marketing support for content, automations, AI clone videos, and lead follow-up." },
    { q: "Are there refunds?", a: "Due to the digital nature of this product and instant access delivery, all sales are final." },
  ],
  finalCta: "Join The Dollhouse Today",
  accent: "brand",
  productImage: brandKitImage,
};

export const workbookProduct: BrandProduct = {
  eyebrow: "Interactive Brand Workbook",
  name: "The Dollhouse Workbook",
  shortName: "Workbook",
  price: "$47",
  regular: "$261",
  value: "Interactive workbook · bonus PDF included",
  checkoutUrl: "",
  tagline: "Not a PDF download. A guided live experience that walks you through every brand decision — one clear prompt at a time.",
  intro: "This is for the beginner who already knows what she wants to build, but does not know where to start. Walk through the prompts, organize your answers, and leave with a brand foundation you can actually use.",
  painHeadline: "Stop trying to hold your entire business in your head.",
  painBody: "The workbook helps you stop trying to hold the whole business in your head. It gives you a calm, structured place to define your audience, offer, value, positioning, brand voice, content pillars, and launch direction.",
  imageTitle: "Workbook",
  imageSubtitle: "A guided brand-building experience for turning your ideas into a clear business foundation.",
  imageItems: ["Brand foundation", "Audience clarity", "Offer planning", "Bonus PDF"],
  insideTitle: "A guided path from idea to brand clarity.",
  inside: [
    { title: "Brand Foundation", body: "Clarify the mission, values, story, and direction behind the brand you want to build." },
    { title: "Audience & Positioning", body: "Understand who you serve, what they want, and how your brand should be positioned in their mind." },
    { title: "Offer Clarity", body: "Map your product, service, transformation, pricing thoughts, and the value your audience is buying." },
    { title: "Content Pillars", body: "Turn your brand direction into content themes you can actually post from with confidence." },
    { title: "Launch Readiness", body: "Use the checklist-style guidance to see what still needs to be built before you promote." },
    { title: "Saveable Worksheets", body: "Keep your answers organized in one place with a workbook-style experience plus bonus PDF support." },
  ],
  outcomes: [
    "Know what your brand stands for and who it is really for.",
    "Stop second guessing your offer, content direction, and message.",
    "Walk away with answers, not more questions — and a foundation you can actually build on.",
    "Create the foundation before moving into the Brand Kit or managed marketing.",
  ],
  perfectFor: [
    "Beginners who want a lower-priced entry point before the full Brand Kit.",
    "New business owners with ideas everywhere and no organized plan yet.",
    "Creators, service providers, boutiques, and digital product sellers building their first serious brand.",
    "Anyone who likes guided prompts, worksheets, and a slower strategy-building process.",
  ],
  bonuses: [
    "Bonus PDF workbook",
    "Guided brand prompts",
    "Audience clarity questions",
    "Content pillar planner",
    "Launch readiness checklist",
    "Brand positioning support",
  ],
  faqs: [
    { q: "Is this different from the Brand Kit?", a: "Yes. The workbook focuses on the business foundation and guided planning. The Brand Kit is the fuller private strategy suite with more rooms and web-app structure." },
    { q: "Do I need to print anything?", a: "No. The workbook is designed as an interactive web app, with a bonus PDF if you prefer to think on paper." },
    { q: "Is this good if I am brand new?", a: "Yes. It is especially helpful if you know you want to build something but need structure before choosing visuals or hiring help." },
    { q: "What should I buy after this?", a: "If you want the full strategy experience, move into the Brand Kit. If your business is already live, apply for managed marketing support." },
    { q: "Are there refunds?", a: "Because this is a digital product with instant access, all sales are final." },
  ],
  finalCta: "Get the Workbook",
  accent: "workbook",
  productImage: workbookImage,
};

export const aiPromptKitProduct: BrandProduct = {
  eyebrow: "AI Prompt Kit",
  name: "The Dollhouse AI Prompt Kit",
  shortName: "AI Kit",
  price: "$17",
  value: "50+ ready-to-use prompts · instant access",
  checkoutUrl: "",
  tagline: "Not random prompts. A structured prompt system built for your brand, your offer, and your voice — so your AI output actually sounds like you.",
  intro: "This is the quick-start kit for beginners who already have an idea or brand direction and need help turning it into polished content, faster. Copy the prompt, customise the details, and let AI help you get unstuck.",
  painHeadline: "Stop asking AI the wrong questions.",
  painBody: "You do not need more generic AI prompts. You need prompts that help you think through your brand, offers, content, launch, and marketing in a way that actually sounds like you.",
  imageTitle: "Prompt Kit",
  imageSubtitle: "50+ ready-to-use prompts across brand, content, offer, email, and launch planning.",
  imageItems: ["50+ prompts", "8 prompt rooms", "Captions + hooks", "Launch copy"],
  insideTitle: "A prompt library built for brand-building, not random content.",
  inside: [
    { title: "Caption & Hook Prompts", body: "Create post ideas, hooks, captions, carousel angles, and short-form video directions with less overthinking." },
    { title: "Offer Copy Prompts", body: "Generate product descriptions, value statements, sales angles, and offer messaging that connect to the buyer." },
    { title: "Email & SMS Prompts", body: "Draft nurture emails, launch announcements, reminders, and follow-up messages without starting from scratch." },
    { title: "Brand Voice Prompts", body: "Shape your tone, messaging, and content language so your AI output sounds more aligned." },
    { title: "Launch Prompts", body: "Plan launch content, promo sequences, urgency angles, and selling moments with structure." },
    { title: "AI Workflow Support", body: "Use prompts in ChatGPT or your preferred AI tool to move faster while keeping the strategy grounded." },
  ],
  outcomes: [
    "Walk away creating content in minutes, not hours — with outputs that actually sound like your brand.",
    "Turn your ideas into captions, hooks, emails, and sales copy.",
    "Use AI with better instructions instead of vague one-line prompts.",
    "Pair it with the Workbook or Brand Kit so your prompts are based on a real foundation.",
  ],
  perfectFor: [
    "Creators and beginners who know what they want to say but freeze when it is time to write.",
    "Business owners who need captions, hooks, emails, and offer copy without hiring a copywriter yet.",
    "Anyone using ChatGPT who wants better outputs from clearer prompt structure.",
    "Brand Room buyers who want faster content after finishing their foundation.",
  ],
  bonuses: [
    "Caption prompts",
    "Hook prompts",
    "Offer copy prompts",
    "Launch planning prompts",
    "Brand voice prompts",
  ],
  faqs: [
    { q: "Do I need paid ChatGPT?", a: "No. You can use these prompts with the free version of ChatGPT or your preferred AI writing tool." },
    { q: "Is this generic AI content?", a: "No. The prompts are designed to help you add your audience, offer, tone, and brand details so the output becomes more specific." },
    { q: "Does this replace the Workbook or Brand Kit?", a: "No. It pairs best with them. The stronger your foundation is, the stronger your AI outputs will be." },
    { q: "Can I use this for my business if I already have one?", a: "Yes. It is useful for active businesses that need content ideas, launch copy, and message support quickly." },
    { q: "Are there refunds?", a: "Because this is a digital product with instant access, all sales are final." },
  ],
  finalCta: "Get the Prompts",
  accent: "ai",
  productImage: aiPromptKitImage,
};
