/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StarterKitRouteImport } from './routes/starter-kit'
import { Route as IndexRouteImport } from './routes/index'

const StarterKitRoute = StarterKitRouteImport.update({
  id: '/starter-kit',
  path: '/starter-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/starter-kit': typeof StarterKitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/starter-kit': typeof StarterKitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/starter-kit': typeof StarterKitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/starter-kit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/starter-kit'
  id: '__root__' | '/' | '/starter-kit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StarterKitRoute: typeof StarterKitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/starter-kit': {
      id: '/starter-kit'
      path: '/starter-kit'
      fullPath: '/starter-kit'
      preLoaderRoute: typeof StarterKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StarterKitRoute: StarterKitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
