/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SoftwareRouteImport } from './routes/software'
import { Route as SocietyRouteImport } from './routes/society'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as FoundationRouteImport } from './routes/foundation'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BrandRoomRouteImport } from './routes/brand-room'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AiCloneRouteImport } from './routes/ai-clone'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SystemsServiceRouteImport } from './routes/systems_.$service'
import { Route as StanstoreWorkbookRouteImport } from './routes/stanstore_.workbook'
import { Route as StanstoreBrandKitRouteImport } from './routes/stanstore_.brand-kit'
import { Route as StanstoreAiPromptKitRouteImport } from './routes/stanstore_.ai-prompt-kit'
import { Route as CheckoutProductRouteImport } from './routes/checkout_.$product'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as BrandRoomWorkbookRouteImport } from './routes/brand-room_.workbook'
import { Route as BrandRoomBrandWorkbookRouteImport } from './routes/brand-room_.brand-workbook'
import { Route as BrandRoomBrandKitRouteImport } from './routes/brand-room_.brand-kit'
import { Route as BrandRoomAiPromptKitRouteImport } from './routes/brand-room_.ai-prompt-kit'
import { Route as BlogSocialMediaMarketingYorkRegionRouteImport } from './routes/blog_.social-media-marketing-york-region'
import { Route as BlogSocialMediaMarketingCostTorontoRouteImport } from './routes/blog_.social-media-marketing-cost-toronto'
import { Route as BlogSocialMediaMarketingAgencyTorontoRouteImport } from './routes/blog_.social-media-marketing-agency-toronto'
import { Route as BlogAiVideoMarketingTorontoRouteImport } from './routes/blog_.ai-video-marketing-toronto'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareRoute = SoftwareRouteImport.update({
  id: '/software',
  path: '/software',
  getParentRoute: () => rootRouteImport,
} as any)
const SocietyRoute = SocietyRouteImport.update({
  id: '/society',
  path: '/society',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationRoute = FoundationRouteImport.update({
  id: '/foundation',
  path: '/foundation',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoomRoute = BrandRoomRouteImport.update({
  id: '/brand-room',
  path: '/brand-room',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCloneRoute = AiCloneRouteImport.update({
  id: '/ai-clone',
  path: '/ai-clone',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsServiceRoute = SystemsServiceRouteImport.update({
  id: '/systems_/$service',
  path: '/systems/$service',
  getParentRoute: () => rootRouteImport,
} as any)
const StanstoreWorkbookRoute = StanstoreWorkbookRouteImport.update({
  id: '/stanstore_/workbook',
  path: '/stanstore/workbook',
  getParentRoute: () => rootRouteImport,
} as any)
const StanstoreBrandKitRoute = StanstoreBrandKitRouteImport.update({
  id: '/stanstore_/brand-kit',
  path: '/stanstore/brand-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const StanstoreAiPromptKitRoute = StanstoreAiPromptKitRouteImport.update({
  id: '/stanstore_/ai-prompt-kit',
  path: '/stanstore/ai-prompt-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutProductRoute = CheckoutProductRouteImport.update({
  id: '/checkout_/$product',
  path: '/checkout/$product',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoomWorkbookRoute = BrandRoomWorkbookRouteImport.update({
  id: '/brand-room_/workbook',
  path: '/brand-room/workbook',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoomBrandWorkbookRoute = BrandRoomBrandWorkbookRouteImport.update({
  id: '/brand-room_/brand-workbook',
  path: '/brand-room/brand-workbook',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoomBrandKitRoute = BrandRoomBrandKitRouteImport.update({
  id: '/brand-room_/brand-kit',
  path: '/brand-room/brand-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoomAiPromptKitRoute = BrandRoomAiPromptKitRouteImport.update({
  id: '/brand-room_/ai-prompt-kit',
  path: '/brand-room/ai-prompt-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSocialMediaMarketingYorkRegionRoute =
  BlogSocialMediaMarketingYorkRegionRouteImport.update({
    id: '/blog_/social-media-marketing-york-region',
    path: '/blog/social-media-marketing-york-region',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogSocialMediaMarketingCostTorontoRoute =
  BlogSocialMediaMarketingCostTorontoRouteImport.update({
    id: '/blog_/social-media-marketing-cost-toronto',
    path: '/blog/social-media-marketing-cost-toronto',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogSocialMediaMarketingAgencyTorontoRoute =
  BlogSocialMediaMarketingAgencyTorontoRouteImport.update({
    id: '/blog_/social-media-marketing-agency-toronto',
    path: '/blog/social-media-marketing-agency-toronto',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogAiVideoMarketingTorontoRoute =
  BlogAiVideoMarketingTorontoRouteImport.update({
    id: '/blog_/ai-video-marketing-toronto',
    path: '/blog/ai-video-marketing-toronto',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-clone': typeof AiCloneRoute
  '/blog': typeof BlogRoute
  '/brand-room': typeof BrandRoomRoute
  '/careers': typeof CareersRoute
  '/foundation': typeof FoundationRoute
  '/onboarding': typeof OnboardingRoute
  '/playbook': typeof PlaybookRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/services': typeof ServicesRoute
  '/society': typeof SocietyRoute
  '/software': typeof SoftwareRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/vault': typeof VaultRoute
  '/blog/ai-video-marketing-toronto': typeof BlogAiVideoMarketingTorontoRoute
  '/blog/social-media-marketing-agency-toronto': typeof BlogSocialMediaMarketingAgencyTorontoRoute
  '/blog/social-media-marketing-cost-toronto': typeof BlogSocialMediaMarketingCostTorontoRoute
  '/blog/social-media-marketing-york-region': typeof BlogSocialMediaMarketingYorkRegionRoute
  '/brand-room/ai-prompt-kit': typeof BrandRoomAiPromptKitRoute
  '/brand-room/brand-kit': typeof BrandRoomBrandKitRoute
  '/brand-room/brand-workbook': typeof BrandRoomBrandWorkbookRoute
  '/brand-room/workbook': typeof BrandRoomWorkbookRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/checkout/$product': typeof CheckoutProductRoute
  '/stanstore/ai-prompt-kit': typeof StanstoreAiPromptKitRoute
  '/stanstore/brand-kit': typeof StanstoreBrandKitRoute
  '/stanstore/workbook': typeof StanstoreWorkbookRoute
  '/systems/$service': typeof SystemsServiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-clone': typeof AiCloneRoute
  '/blog': typeof BlogRoute
  '/brand-room': typeof BrandRoomRoute
  '/careers': typeof CareersRoute
  '/foundation': typeof FoundationRoute
  '/onboarding': typeof OnboardingRoute
  '/playbook': typeof PlaybookRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/services': typeof ServicesRoute
  '/society': typeof SocietyRoute
  '/software': typeof SoftwareRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/vault': typeof VaultRoute
  '/blog/ai-video-marketing-toronto': typeof BlogAiVideoMarketingTorontoRoute
  '/blog/social-media-marketing-agency-toronto': typeof BlogSocialMediaMarketingAgencyTorontoRoute
  '/blog/social-media-marketing-cost-toronto': typeof BlogSocialMediaMarketingCostTorontoRoute
  '/blog/social-media-marketing-york-region': typeof BlogSocialMediaMarketingYorkRegionRoute
  '/brand-room/ai-prompt-kit': typeof BrandRoomAiPromptKitRoute
  '/brand-room/brand-kit': typeof BrandRoomBrandKitRoute
  '/brand-room/brand-workbook': typeof BrandRoomBrandWorkbookRoute
  '/brand-room/workbook': typeof BrandRoomWorkbookRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/checkout/$product': typeof CheckoutProductRoute
  '/stanstore/ai-prompt-kit': typeof StanstoreAiPromptKitRoute
  '/stanstore/brand-kit': typeof StanstoreBrandKitRoute
  '/stanstore/workbook': typeof StanstoreWorkbookRoute
  '/systems/$service': typeof SystemsServiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-clone': typeof AiCloneRoute
  '/blog': typeof BlogRoute
  '/brand-room': typeof BrandRoomRoute
  '/careers': typeof CareersRoute
  '/foundation': typeof FoundationRoute
  '/onboarding': typeof OnboardingRoute
  '/playbook': typeof PlaybookRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/services': typeof ServicesRoute
  '/society': typeof SocietyRoute
  '/software': typeof SoftwareRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/vault': typeof VaultRoute
  '/blog_/ai-video-marketing-toronto': typeof BlogAiVideoMarketingTorontoRoute
  '/blog_/social-media-marketing-agency-toronto': typeof BlogSocialMediaMarketingAgencyTorontoRoute
  '/blog_/social-media-marketing-cost-toronto': typeof BlogSocialMediaMarketingCostTorontoRoute
  '/blog_/social-media-marketing-york-region': typeof BlogSocialMediaMarketingYorkRegionRoute
  '/brand-room_/ai-prompt-kit': typeof BrandRoomAiPromptKitRoute
  '/brand-room_/brand-kit': typeof BrandRoomBrandKitRoute
  '/brand-room_/brand-workbook': typeof BrandRoomBrandWorkbookRoute
  '/brand-room_/workbook': typeof BrandRoomWorkbookRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/checkout_/$product': typeof CheckoutProductRoute
  '/stanstore_/ai-prompt-kit': typeof StanstoreAiPromptKitRoute
  '/stanstore_/brand-kit': typeof StanstoreBrandKitRoute
  '/stanstore_/workbook': typeof StanstoreWorkbookRoute
  '/systems_/$service': typeof SystemsServiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-clone'
    | '/blog'
    | '/brand-room'
    | '/careers'
    | '/foundation'
    | '/onboarding'
    | '/playbook'
    | '/privacy'
    | '/quiz'
    | '/services'
    | '/society'
    | '/software'
    | '/terms'
    | '/thank-you'
    | '/vault'
    | '/blog/ai-video-marketing-toronto'
    | '/blog/social-media-marketing-agency-toronto'
    | '/blog/social-media-marketing-cost-toronto'
    | '/blog/social-media-marketing-york-region'
    | '/brand-room/ai-prompt-kit'
    | '/brand-room/brand-kit'
    | '/brand-room/brand-workbook'
    | '/brand-room/workbook'
    | '/checkout/success'
    | '/checkout/$product'
    | '/stanstore/ai-prompt-kit'
    | '/stanstore/brand-kit'
    | '/stanstore/workbook'
    | '/systems/$service'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-clone'
    | '/blog'
    | '/brand-room'
    | '/careers'
    | '/foundation'
    | '/onboarding'
    | '/playbook'
    | '/privacy'
    | '/quiz'
    | '/services'
    | '/society'
    | '/software'
    | '/terms'
    | '/thank-you'
    | '/vault'
    | '/blog/ai-video-marketing-toronto'
    | '/blog/social-media-marketing-agency-toronto'
    | '/blog/social-media-marketing-cost-toronto'
    | '/blog/social-media-marketing-york-region'
    | '/brand-room/ai-prompt-kit'
    | '/brand-room/brand-kit'
    | '/brand-room/brand-workbook'
    | '/brand-room/workbook'
    | '/checkout/success'
    | '/checkout/$product'
    | '/stanstore/ai-prompt-kit'
    | '/stanstore/brand-kit'
    | '/stanstore/workbook'
    | '/systems/$service'
  id:
    | '__root__'
    | '/'
    | '/ai-clone'
    | '/blog'
    | '/brand-room'
    | '/careers'
    | '/foundation'
    | '/onboarding'
    | '/playbook'
    | '/privacy'
    | '/quiz'
    | '/services'
    | '/society'
    | '/software'
    | '/terms'
    | '/thank-you'
    | '/vault'
    | '/blog_/ai-video-marketing-toronto'
    | '/blog_/social-media-marketing-agency-toronto'
    | '/blog_/social-media-marketing-cost-toronto'
    | '/blog_/social-media-marketing-york-region'
    | '/brand-room_/ai-prompt-kit'
    | '/brand-room_/brand-kit'
    | '/brand-room_/brand-workbook'
    | '/brand-room_/workbook'
    | '/checkout/success'
    | '/checkout_/$product'
    | '/stanstore_/ai-prompt-kit'
    | '/stanstore_/brand-kit'
    | '/stanstore_/workbook'
    | '/systems_/$service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiCloneRoute: typeof AiCloneRoute
  BlogRoute: typeof BlogRoute
  BrandRoomRoute: typeof BrandRoomRoute
  CareersRoute: typeof CareersRoute
  FoundationRoute: typeof FoundationRoute
  OnboardingRoute: typeof OnboardingRoute
  PlaybookRoute: typeof PlaybookRoute
  PrivacyRoute: typeof PrivacyRoute
  QuizRoute: typeof QuizRoute
  ServicesRoute: typeof ServicesRoute
  SocietyRoute: typeof SocietyRoute
  SoftwareRoute: typeof SoftwareRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  VaultRoute: typeof VaultRoute
  BlogAiVideoMarketingTorontoRoute: typeof BlogAiVideoMarketingTorontoRoute
  BlogSocialMediaMarketingAgencyTorontoRoute: typeof BlogSocialMediaMarketingAgencyTorontoRoute
  BlogSocialMediaMarketingCostTorontoRoute: typeof BlogSocialMediaMarketingCostTorontoRoute
  BlogSocialMediaMarketingYorkRegionRoute: typeof BlogSocialMediaMarketingYorkRegionRoute
  BrandRoomAiPromptKitRoute: typeof BrandRoomAiPromptKitRoute
  BrandRoomBrandKitRoute: typeof BrandRoomBrandKitRoute
  BrandRoomBrandWorkbookRoute: typeof BrandRoomBrandWorkbookRoute
  BrandRoomWorkbookRoute: typeof BrandRoomWorkbookRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  CheckoutProductRoute: typeof CheckoutProductRoute
  StanstoreAiPromptKitRoute: typeof StanstoreAiPromptKitRoute
  StanstoreBrandKitRoute: typeof StanstoreBrandKitRoute
  StanstoreWorkbookRoute: typeof StanstoreWorkbookRoute
  SystemsServiceRoute: typeof SystemsServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software': {
      id: '/software'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof SoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/society': {
      id: '/society'
      path: '/society'
      fullPath: '/society'
      preLoaderRoute: typeof SocietyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundation': {
      id: '/foundation'
      path: '/foundation'
      fullPath: '/foundation'
      preLoaderRoute: typeof FoundationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-room': {
      id: '/brand-room'
      path: '/brand-room'
      fullPath: '/brand-room'
      preLoaderRoute: typeof BrandRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-clone': {
      id: '/ai-clone'
      path: '/ai-clone'
      fullPath: '/ai-clone'
      preLoaderRoute: typeof AiCloneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems_/$service': {
      id: '/systems_/$service'
      path: '/systems/$service'
      fullPath: '/systems/$service'
      preLoaderRoute: typeof SystemsServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stanstore_/workbook': {
      id: '/stanstore_/workbook'
      path: '/stanstore/workbook'
      fullPath: '/stanstore/workbook'
      preLoaderRoute: typeof StanstoreWorkbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stanstore_/brand-kit': {
      id: '/stanstore_/brand-kit'
      path: '/stanstore/brand-kit'
      fullPath: '/stanstore/brand-kit'
      preLoaderRoute: typeof StanstoreBrandKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stanstore_/ai-prompt-kit': {
      id: '/stanstore_/ai-prompt-kit'
      path: '/stanstore/ai-prompt-kit'
      fullPath: '/stanstore/ai-prompt-kit'
      preLoaderRoute: typeof StanstoreAiPromptKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout_/$product': {
      id: '/checkout_/$product'
      path: '/checkout/$product'
      fullPath: '/checkout/$product'
      preLoaderRoute: typeof CheckoutProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-room_/workbook': {
      id: '/brand-room_/workbook'
      path: '/brand-room/workbook'
      fullPath: '/brand-room/workbook'
      preLoaderRoute: typeof BrandRoomWorkbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-room_/brand-workbook': {
      id: '/brand-room_/brand-workbook'
      path: '/brand-room/brand-workbook'
      fullPath: '/brand-room/brand-workbook'
      preLoaderRoute: typeof BrandRoomBrandWorkbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-room_/brand-kit': {
      id: '/brand-room_/brand-kit'
      path: '/brand-room/brand-kit'
      fullPath: '/brand-room/brand-kit'
      preLoaderRoute: typeof BrandRoomBrandKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-room_/ai-prompt-kit': {
      id: '/brand-room_/ai-prompt-kit'
      path: '/brand-room/ai-prompt-kit'
      fullPath: '/brand-room/ai-prompt-kit'
      preLoaderRoute: typeof BrandRoomAiPromptKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/social-media-marketing-york-region': {
      id: '/blog_/social-media-marketing-york-region'
      path: '/blog/social-media-marketing-york-region'
      fullPath: '/blog/social-media-marketing-york-region'
      preLoaderRoute: typeof BlogSocialMediaMarketingYorkRegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/social-media-marketing-cost-toronto': {
      id: '/blog_/social-media-marketing-cost-toronto'
      path: '/blog/social-media-marketing-cost-toronto'
      fullPath: '/blog/social-media-marketing-cost-toronto'
      preLoaderRoute: typeof BlogSocialMediaMarketingCostTorontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/social-media-marketing-agency-toronto': {
      id: '/blog_/social-media-marketing-agency-toronto'
      path: '/blog/social-media-marketing-agency-toronto'
      fullPath: '/blog/social-media-marketing-agency-toronto'
      preLoaderRoute: typeof BlogSocialMediaMarketingAgencyTorontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/ai-video-marketing-toronto': {
      id: '/blog_/ai-video-marketing-toronto'
      path: '/blog/ai-video-marketing-toronto'
      fullPath: '/blog/ai-video-marketing-toronto'
      preLoaderRoute: typeof BlogAiVideoMarketingTorontoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiCloneRoute: AiCloneRoute,
  BlogRoute: BlogRoute,
  BrandRoomRoute: BrandRoomRoute,
  CareersRoute: CareersRoute,
  FoundationRoute: FoundationRoute,
  OnboardingRoute: OnboardingRoute,
  PlaybookRoute: PlaybookRoute,
  PrivacyRoute: PrivacyRoute,
  QuizRoute: QuizRoute,
  ServicesRoute: ServicesRoute,
  SocietyRoute: SocietyRoute,
  SoftwareRoute: SoftwareRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  VaultRoute: VaultRoute,
  BlogAiVideoMarketingTorontoRoute: BlogAiVideoMarketingTorontoRoute,
  BlogSocialMediaMarketingAgencyTorontoRoute:
    BlogSocialMediaMarketingAgencyTorontoRoute,
  BlogSocialMediaMarketingCostTorontoRoute:
    BlogSocialMediaMarketingCostTorontoRoute,
  BlogSocialMediaMarketingYorkRegionRoute:
    BlogSocialMediaMarketingYorkRegionRoute,
  BrandRoomAiPromptKitRoute: BrandRoomAiPromptKitRoute,
  BrandRoomBrandKitRoute: BrandRoomBrandKitRoute,
  BrandRoomBrandWorkbookRoute: BrandRoomBrandWorkbookRoute,
  BrandRoomWorkbookRoute: BrandRoomWorkbookRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  CheckoutProductRoute: CheckoutProductRoute,
  StanstoreAiPromptKitRoute: StanstoreAiPromptKitRoute,
  StanstoreBrandKitRoute: StanstoreBrandKitRoute,
  StanstoreWorkbookRoute: StanstoreWorkbookRoute,
  SystemsServiceRoute: SystemsServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
